- name: copy sshd_config
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    mode: 0644
  register: change_sshd

- name: Restart service sshd, to pick up config changes
  systemd:
    state: restarted
    name: ssh
  when: change_sshd.changed