- name: Install "ntpdate" package
  apt:
    name: "ntpdate"
    force_apt_get: yes

- name: Time synchronization on the server
  command: ntpdate -u 0.debian.pool.ntp.org
  changed_when: false

- name: Remove "ntp" package
  apt:
    name: ntp
    state: absent

- name: Remove file ntp.conf
  ansible.builtin.file:
    path: /etc/ntp.conf
    state: absent

- name: file for access registry
  template:
    src: "timesyncd.conf.j2"
    dest: "/etc/systemd/timesyncd.conf"
    mode: 0644

- name: Enable time synchronization on the server
  command: timedatectl set-ntp true
  changed_when: false

- name: Restart systemd services systemd-timesyncd
  systemd:
    state: restarted
    name: "systemd-timesyncd"
    enabled: yes
  changed_when: false
